# name: Springboot Java CI/CD
#
# on:
#   push:
#     branches:
#       - main
#
#   pull_request:
#     branches:
#       - main
#
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#
#
#       - name: Setup Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: 17
#
#
#       - name: Build Application
#         run: mvn clean -B package
#
#
#       - name: Build Docker Image
#         run: docker build -t abubakar2001rip/coffeehouse-app:v1 .
